[credentials]
names = ["Time Iteca"]
usernames = ["iteca"]
# HASH da senha 'guarana' (Criptografada!)
passwords = ["$2b$12$x/8mHqasmFA0I9Y2xJ1N7uhVAjHTzv2rE52ryUpe9w5R/0IpZBq6G"] 

[authenticator]
cookie_name = "iteca_auth"
# ⚠️ COLOQUE UMA CHAVE SECRETA LONGA E ALEATÓRIA AQUI!
cookie_key = "MINHA_CHAVE_SECRETA_DO_COOKIE" 
cookie_expiry_days = 30
preauthorized = {emails = []}